---
- name: Base Ubuntu setup
  hosts: all
  become: True
  become_user: root

  gather_facts: false
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)
      changed_when: False
    - setup: # aka gather_facts

  roles:
  # All Ubuntu installs should get 'base', 'certificates', and 'snmp'
  - base
  - certificates
  - snmp
  # Uncomment below if Apache/PHP should be installed
  #- apache-php
  # Uncomment below if this machine should be joined to the domain
  #- non-domain-server
  # Uncomment below if this machine should be joined to the domain
  #- domain
