#!/bin/bash

echo -e "\e[1;3;34m************************************************\e[0m"
echo -e "\e[1;3;34m*\e[0m This system is for authorized use only.      \e[1;3;34m*\e[0m"
echo -e "\e[1;3;34m*\e[0m All activity is monitored and recorded.      \e[1;3;34m*\e[0m"
echo -e "\e[1;3;34m*\e[0m Anyone using this system expressly consents  \e[1;3;34m*\e[0m"
echo -e "\e[1;3;34m*\e[0m to such monitoring and is advised that if    \e[1;3;34m*\e[0m"
echo -e "\e[1;3;34m*\e[0m it reveals evidence of criminal activity,    \e[1;3;34m*\e[0m"
echo -e "\e[1;3;34m*\e[0m such information will be provided to law     \e[1;3;34m*\e[0m"
echo -e "\e[1;3;34m*\e[0m enforcement officials.                       \e[1;3;34m*\e[0m"
echo -e "\e[1;3;34m************************************************\e[0m"
